version: "3"
volumes:
  node_modules_volume:
services:
  nextjs:
    build: ./docker/
    container_name: weather-app-master
    ports:
      - "4001:3000"
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app
      - node_modules_volume:/usr/src/app/node_modules
    tty: true
    stdin_open: true
    command: "yarn dev"
